"""
Stream bridge module for handling ZMQ_STREAM sockets and TCP connections.

Provides helpers for managing byte-stream framing over ZMQ_STREAM.
"""

import asyncio
from dataclasses import dataclass
from typing import Callable, Optional
import zmq


@dataclass
class StreamEvent:
    """Event generated by a ZMQ_STREAM socket."""
    stream_id: str
    event_type: str  # "CONNECT", "DISCONNECT", "CLOSE"
    remote_addr: Optional[str] = None
    local_addr: Optional[str] = None


async def recv_stream(
    sock: zmq.Socket,
    callback: Callable[[bytes], None],
    timeout_ms: int = 100,
) -> None:
    """
    Continuously receive messages on a ZMQ_STREAM socket and pass raw bytes to callback.

    ZMQ_STREAM emits events before data frames:
      - EVENT_CONNECT (stream opens to peer)
      - EVENT_DISCONNECT (stream closed by peer)
      - DATA frames (raw TCP payload)

    Args:
        sock: ZMQ_STREAM socket
        callback: Function to call with each frame's raw bytes
        timeout_ms: Poll timeout in milliseconds
    """
    poller = zmq.Poller()
    poller.register(sock, zmq.POLLIN)

    while True:
        socks = dict(poller.poll(timeout=timeout_ms))
        if sock in socks and socks[sock] == zmq.POLLIN:
            try:
                frame = sock.recv_multipart(zmq.NOBLOCK)

                # Frame 0 is the event type (e.g., EVENT_CONNECT, EVENT_DISCONNECT, or empty for data)
                evt_type, stream_id, *rest = frame

                # Handle disconnect events (frame[0] = b"EVENT_DISCONNECT")
                if evt_type == EventNames.EVENT_DISCONNECT:
                    print(f"[STREAM] Disconnected from {stream_id.decode()}", flush=True)
                    continue

                # For data frames, frame 0 is empty and rest contains the actual payload
                if len(rest) > 0:
                    callback(bytes.fromhex(rest[0].decode()) if isinstance(rest[0], str) else rest[0])
                elif evt_type == b"":
                    # Empty event with stream_id - likely data frame, read next as payload
                    try:
                        payload = sock.recv_multipart(zmq.NOBLOCK)
                        callback(payload[-1] if len(payload) > 1 else payload[0])
                    except zmq.ZMQError:
                        pass

            except zmq.ZMQError as e:
                print(f"[STREAM] recv error: {e}", flush=True)


class StreamIdentityMap:
    """
    Maps stream identifiers to connection IDs for multiplexed connections.

    Used by both local and remote forwarders to correlate TCP connections
    with the underlying ZMQ_STREAM frames.
    """

    def __init__(self):
        self._lock = asyncio.Lock()
        self._map: dict[str, tuple[str, bytes]] = {}  # stream_id -> (conn_id, target_addr)
        self._conn_to_stream: dict[str, str] = {}  # conn_id -> stream_id

    async def register(
        self,
        stream_id: str,
        conn_id: str,
        target_addr: Optional[str] = None,
    ) -> None:
        """Register a new connection."""
        async with self._lock:
            self._map[stream_id] = (conn_id, target_addr or "")
            self._conn_to_stream[conn_id] = stream_id

    async def unregister(self, conn_id: str) -> Optional[str]:
        """Unregister a connection and return the stream_id."""
        async with self._lock:
            for stream_id, (cid, _) in list(self._map.items()):
                if cid == conn_id:
                    del self._map[stream_id]
                    del self._conn_to_stream[conn_id]
                    return stream_id
            return None

    def get_target(self, stream_id: str) -> Optional[str]:
        """Get the target address for a stream."""
        return self._map.get(stream_id, ("", ""))[1]

    def get_stream_id(self, conn_id: str) -> Optional[str]:
        """Get stream ID for a connection."""
        return self._conn_to_stream.get(conn_id)


class EventNames:
    """Enum-like class for ZMQ_STREAM events."""

    EVENT_CONNECT = b"EVENT_CONNECT"
    EVENT_DISCONNECT = b"EVENT_DISCONNECT"

    @classmethod
    def from_bytes(cls, data: bytes) -> str:
        try:
            return data.decode() if isinstance(data, bytes) else data
        except (ValueError, AttributeError):
            return str(data)
