[package]
name = "tunnel-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
tokio.workspace = true
rmp-serde.workspace = true
serde.workspace = true
tracing.workspace = true
uuid.workspace = true
anyhow.workspace = true
zmq = { version = "0.10", default-features = false }
tunnel-common = { path = "../tunnel-common" }
toml = "0.8"

[dev-dependencies]
rand = "0.8"
