[package]
name = "tunnel-server"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde.workspace = true
clap.workspace = true
anyhow.workspace = true
toml.workspace = true
zmq = { version = "0.10", default-features = false }
uuid.workspace = true
tunnel-common = { path = "../tunnel-common" }
bytes = "1"
rmp-serde = "1"

[dev-dependencies]
toml = "0.8"
