#ifndef UTILS_H
#define UTILS_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// Logging levels
#define LOG_DEBUG 0
#define LOG_INFO 1
#define LOG_WARN 2
#define LOG_ERROR 3

typedef enum {
    LEVEL_DEBUG = LOG_DEBUG,
    LEVEL_INFO = LOG_INFO,
    LEVEL_WARN = LOG_WARN,
    LEVEL_ERROR = LOG_ERROR
} LogLevel;

// Initialize logging with level (set to 0 for DEBUG)
void utils_init(LogLevel level);

// Cleanup logging
void utils_cleanup(void);

// Log a message
void log_message(LogLevel level, const char *msg);

// Generate a UUID as string (output format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx)
char* generate_uuid(void);

// Free UUID string generated by generate_uuid
void free_uuid(char *uuid);

// Simple string comparison (case-sensitive)
int str_equal(const char *a, const char *b);

// String length of input or maxlen if empty/NULL
size_t str_len(const char *str);

#endif /* UTILS_H */
